AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function Template
Parameters:

  Runtime:
    Type: String
    Default: nodejs12.x

  Timeout:
    Type: String
    Description: Time for timeout in seconds
    Default: 120

  MemorySize:
    Type: Number
    Description: Size the memory for function
    Default: 128

  Versao:
    Type: String
    Default: 1.0

  Env:
    Type: String
    Default: Dev

  Handler:
    Type: String
    Default: index.handler

  FunctionName:
    Type: String
    Default: testCF
  
  BucketName:
    Type: String

  S3Key:
    Type: String

  Service:
    Type: String


Resources:

  Function: 
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: !Ref Handler
      Role: !GetAtt Role.Arn
      Code: 
        S3Bucket: !Ref BucketName
        S3Key: !Ref S3Key
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
      MemorySize: !Ref MemorySize
      Tags:
        - Key: "env"
          Value: !Ref Env
        - Key: "service"
          Value: !Ref Service

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: !Ref FunctionName
          PolicyDocument:
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:*"
                Resource: "*"
